# Generated by Django 4.1.7 on 2023-05-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plate',
            name='name',
            field=models.TextField(default='', max_length=50),
        ),
    ]
