# Generated by Django 4.1.7 on 2023-05-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_plate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
